/**
 * A list of images for the lightbox and image mosaic
 *
 * react-spring-lightbox only requires the @src and @alt properties,
 * the rest are used by the mosaic gallery for demonstration purposes
 */

const BASE_URL = "https://mochilasmineras.s3.amazonaws.com/mochilas_mineras";

export const mosaicImages = [
  {
    src: `${BASE_URL}/mochila_minera/escondida.jpg`,
    alt: "Escondida",
    caption: "Escondida",
    width: 4,
    height: 3,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/jumbo_codelco.jpg`,
    alt: "Jumbo Codelco",
    caption: "Jumbo Codelco",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/jumbo_minera.jpg`,
    alt: "Jumbo Minera",
    caption: "Jumbo Minera",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/minera_porta_casco.jpg`,
    alt: "Minera porta casco",
    caption: "Minera porta casco",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/pelambres.jpg`,
    alt: "Pelambres",
    caption: "Pelambres",
    width: 8,
    height: 6,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/patrol.jpg`,
    alt: "Patrol",
    caption: "Patrol",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/porta_casco.jpg`,
    alt: "Porta Casco",
    caption: "Porta Casco",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/reflectante_2023.jpg`,
    alt: "Reflectante 2023",
    caption: "Reflectante 2023",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/mochila_minera/urbana.jpg`,
    alt: "Urbana",
    caption: "Urbana",
    width: 3,
    height: 4,
    type: "mochilaMinera",
  },
  {
    src: `${BASE_URL}/bolso/bolso_aviador_1.jpg`,
    alt: "Bolso aviador",
    caption: "Bolso aviador",
    width: 3,
    height: 4,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_aviador_2.jpg`,
    alt: "Bolso aviador 2",
    caption: "Bolso aviador 2",
    width: 3,
    height: 4,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_diario_bomberos.jpg`,
    alt: "Bolso diario bomberos",
    caption: "Bolso diario bomberos",
    width: 4,
    height: 3,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_minero.jpg`,
    alt: "Minero",
    caption: "Minero",
    width: 4,
    height: 3,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_minero_2.jpg`,
    alt: "Minero 2",
    caption: "Minero 2",
    width: 4,
    height: 3,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_mochila_minero.jpg`,
    alt: "Bolso mochila minero",
    caption: "Bolso mochila minero",
    width: 3,
    height: 4,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/bolso_mochila_minero_2.jpg`,
    alt: "Bolso mochila minero 2",
    caption: "Bolso mochila minero 2",
    width: 3,
    height: 4,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/jumbo_bomberos.jpg`,
    alt: "Jumbo Bomberos",
    caption: "Jumbo Bomberos",
    width: 4,
    height: 3,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/mochila_constructor.jpg`,
    alt: "Mochila constructor",
    caption: "Mochila constructor",
    width: 3,
    height: 4,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/bolso/montax.jpg`,
    alt: "Montax",
    caption: "Montax",
    width: 4,
    height: 3,
    type: "bolso",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/banano_codelco.jpg`,
    alt: "Banano codelco",
    caption: "Banano codelco",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/banano_paramedico.jpg`,
    alt: "Banano paramedico",
    caption: "Banano paramedico",
    width: 5,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/neceser_personal.jpg`,
    alt: "Neceser personal",
    caption: "Neceser personal",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/neceser_personal_2.jpg`,
    alt: "Neceser personal 2",
    caption: "Neceser personal 2",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/porta_trompa.jpg`,
    alt: "Porta Trompa",
    caption: "Porta Trompa",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/porta_trompa_2.jpg`,
    alt: "Porta Trompa 2",
    caption: "Porta Trompa 2",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/porta_trompa_3.jpg`,
    alt: "Porta Trompa 3",
    caption: "Porta Trompa 3",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/porta_trompa_banano/training_codelco.jpg`,
    alt: "Training codelco",
    caption: "Training codelco",
    width: 4,
    height: 3,
    type: "portaTrompaBanano",
  },
  {
    src: `${BASE_URL}/rescate/banano_paramedico.jpg`,
    alt: "Banano paramedico",
    caption: "Banano paramedico",
    width: 5,
    height: 3,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/bolso_diario_bomberos.jpg`,
    alt: "Bolso diario bomberos",
    caption: "Bolso diario bomberos",
    width: 4,
    height: 3,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/bolso_paramedico_mediano.jpg`,
    alt: "Bolso paramedico mediano",
    caption: "Bolso paramedico mediano",
    width: 10,
    height: 9,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/bolso_paramedicos.jpg`,
    alt: "Bolso paramedico",
    caption: "Bolso paramedico",
    width: 3,
    height: 4,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/bolso_paramedicos_2.jpg`,
    alt: "Bolso paramedico 2",
    caption: "Bolso paramedico 2",
    width: 3,
    height: 4,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/jumbo_bomberos.jpg`,
    alt: "Jumbo bomberos",
    caption: "Jumbo bomberos",
    width: 4,
    height: 3,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/reflectante_x.jpg`,
    alt: "Reflectante x",
    caption: "Reflectante x",
    width: 3,
    height: 4,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/muslera_emergencia.jpg`,
    alt: "Muslera emergencia",
    caption: "Muslera emergencia",
    width: 4,
    height: 3,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/rescate/rescate_bolso_mochila.jpg`,
    alt: "Rescate bolso mochila",
    caption: "Rescate bolso mochila",
    width: 4,
    height: 4,
    type: "rescate",
  },
  {
    src: `${BASE_URL}/mochila_urbana/clip.jpg`,
    alt: "Clip",
    caption: "Clip",
    width: 4,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/cocacola.jpg`,
    alt: "Cocacola",
    caption: "Cocacola",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/faena_bicolor.jpg`,
    alt: "Faena bicolor",
    caption: "Faena bicolor",
    width: 4,
    height: 3,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/gatorade.png`,
    alt: "Gatorade",
    caption: "Gatorade",
    width: 9,
    height: 10,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/lexus.jpg`,
    alt: "Lexus",
    caption: "Lexus",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/lexus_2020.jpg`,
    alt: "Lexus 2020",
    caption: "Lexus 2020",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/mochila_boca_ancha.jpg`,
    alt: "Mochila boca ancha",
    caption: "Mochila boca ancha",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/mochila_boca_ancha_2.jpg`,
    alt: "Mochila boca ancha",
    caption: "Mochila boca ancha",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/promocion.jpg`,
    alt: "Promocion",
    caption: "Promocion",
    width: 4,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/stock.jpg`,
    alt: "Stock",
    caption: "Stock",
    width: 4,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/tenis.png`,
    alt: "Tenis",
    caption: "Tenis",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/urbana.jpg`,
    alt: "Urbana",
    caption: "Urbana",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },
  {
    src: `${BASE_URL}/mochila_urbana/urbana_2.jpg`,
    alt: "Urbana 2",
    caption: "Urbana 2",
    width: 3,
    height: 4,
    type: "mochilaUrbana",
  },

  //   {
  //     src: `${BASE_URL}banano_bhp.jpeg`,
  //     alt: "Banano BHP",
  //     caption: "Banano BHP",
  //     width: 4,
  //     height: 3,
  //     type: "portaTrompaBanano",
  //   },
  //   {
  //     src: `${BASE_URL}banano_bhp2.jpeg`,
  //     alt: "Banano BHP 2",
  //     caption: "Banano BHP 2",
  //     width: 4,
  //     height: 3,
  //     type: "portaTrompaBanano",
  //   },
  //   {
  //     src: `${BASE_URL}banano_bhp3.jpeg`,
  //     alt: "Banano BHP 3",
  //     caption: "Banano BHP 3",
  //     width: 4,
  //     height: 3,
  //     type: "portaTrompaBanano",
  //   },
  //   {
  //     src: `${BASE_URL}banano_portafiltros.jpeg`,
  //     alt: "Banano Portafiltros 3",
  //     caption: "Banano Portafiltros 3",
  //     width: 4,
  //     height: 3,
  //     type: "portaTrompaBanano",
  //   },
  //   {
  //     src: `${BASE_URL}bolso_saco.jpeg`,
  //     alt: "Bolso Saco",
  //     caption: "Bolso Saco",
  //     width: 3,
  //     height: 4,
  //     type: "bolso",
  //   },
  //   {
  //     src: `${BASE_URL}bolso_saco2.jpeg`,
  //     alt: "Bolso Saco 2",
  //     caption: "Bolso Saco 2",
  //     width: 3,
  //     height: 4,
  //     type: "bolso",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_candelaria.jpeg`,
  //     alt: "Mochila Candelaria",
  //     caption: "Mochila Candelaria",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_centinela.jpeg`,
  //     alt: "Mochila Centinela",
  //     caption: "Mochila Centinela",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_mantosblancos.jpeg`,
  //     alt: "Mochila Mantos Blancos",
  //     caption: "Mochila Mantos Blancos",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_mantosblancos2.jpeg`,
  //     alt: "Mochila Mantos Blancos 2",
  //     caption: "Mochila Mantos Blancos 2",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_maxam.jpeg`,
  //     alt: "Mochila Maxam",
  //     caption: "Mochila Maxam",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_operaciones.jpeg`,
  //     alt: "Mochila Operaciones",
  //     caption: "Mochila Operaciones",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_portacasco.jpeg`,
  //     alt: "Mochila Portacasco",
  //     caption: "Mochila Portacasco",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_portacasco2.jpeg`,
  //     alt: "Mochila Portacasco 2",
  //     caption: "Mochila Portacasco 2",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_portacasco3.jpeg`,
  //     alt: "Mochila Portacasco 3",
  //     caption: "Mochila Portacasco 3",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_portacasco4.jpeg`,
  //     alt: "Mochila Portacasco 4",
  //     caption: "Mochila Portacasco 4",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_transporte.jpeg`,
  //     alt: "Mochila Transporte",
  //     caption: "Mochila Transporte",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila_transporte2.jpeg`,
  //     alt: "Mochila Transporte 2",
  //     caption: "Mochila Transporte 2",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila1.jpeg`,
  //     alt: "Mochila",
  //     caption: "Mochila",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila1_2.jpeg`,
  //     alt: "Mochila 2",
  //     caption: "Mochila 2",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila1_3.jpeg`,
  //     alt: "Mochila 3",
  //     caption: "Mochila 3",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila1_4.jpeg`,
  //     alt: "Mochila 4",
  //     caption: "Mochila 4",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}mochila1_5.jpeg`,
  //     alt: "Mochila 5",
  //     caption: "Mochila 5",
  //     width: 3,
  //     height: 4,
  //     type: "mochila",
  //   },
  //   {
  //     src: `${BASE_URL}morral.jpeg`,
  //     alt: "Morral",
  //     caption: "Morral",
  //     width: 3,
  //     height: 4,
  //     type: "morral",
  //   },
  //   {
  //     src: `${BASE_URL}morral_negro.jpeg`,
  //     alt: "Morral Negro",
  //     caption: "Morral Negro",
  //     width: 3,
  //     height: 4,
  //     type: "morral",
  //   },
];

export const lightboxImages = mosaicImages.map(({ src, alt, caption }) => ({
  src,
  alt,
  caption,
}));
